[workspace]
resolver = "2"
members = [
    "kernel",
    "srv/vfs",
    "srv/fs/fat",
    "srv/fs/tmpfs",
    "drv/pci",
    "drv/pci/ide",
]

[profile.dev]
opt-level = 1

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
