[package]
name = "cyclone"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9"

[build-dependencies]
bindgen = "0.70"

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
