[workspace]
resolver = "2"
members = [
    "krnl",
    #"lib/acpica",
    "lib/multiboot",
    "drv/ide",
    "drv/pci",
    "srv/fs/fat",
]

[profile.dev]
opt-level = 1

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1
