[package]
name = "drv_pci"
version = "0.1.0"
authors = ["Kevin Ludwig <iam@valaphee.com>"]
edition = "2021"
description = "PCI driver for the Meerkat operating system."
license = "Apache-2.0"

[dependencies]
log = { workspace = true }

pio = { workspace = true }
bitflags = { workspace = true }
