[package]
name = "drv_fs"
version = "0.1.0"
authors = ["Kevin Ludwig <iam@valaphee.com>"]
edition = "2021"
description = "File system driver for the Meerkat operating system."
license = "Apache-2.0"

[dependencies]
log = { workspace = true }
