[package]
name = "meerkat_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6"

tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }

spin = "0.9"
acpi = "5.0"

[build-dependencies]
bindgen = "0.70"
