[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i386-unknown-none.json"
rustflags = ["-C", "code-model=kernel"]

[target.i386-unknown-none]
runner = [
    "qemu-system-x86_64",
    "-accel",
    "kvm",
    "-smp",
    "cores=4",
    "-m",
    "8G",
    "-kernel",
]
