[package]
name = "svc_vfs"
version = "0.1.0"
authors = ["Kevin Ludwig <iam@valaphee.com>"]
edition = "2021"
description = "Virtual file system service for the Meerkat operating system."
license = "Apache-2.0"

[dependencies]
tracing = { workspace = true }
